# Generated by Django 4.1.6 on 2023-02-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('cancel', 'cancel')], default='Pending', max_length=50),
        ),
    ]
